---
name: App

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  app:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Go setup
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
          cache-dependency-path: |
            subdir/go.sum
            tools/go.sum`

      - name: Go Verify
        run: go mod verify

      - name: Go Build
        run: go build -v ./...

      - name: GO Vet
        run: go vet ./...

      # - uses: dominikh/staticcheck-action@v1.2.0
      #   with:
      #     version: "2022.1.1"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: latest

      # - name: Run tests
      #   run: go test
