---
name: App

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  app:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Go setup
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
          cache-dependency-path: |
            subdir/go.sum
            tools/go.sum`

      - name: Go Verify
        run: go mod verify

      - name: Go Build
        run: go build -v ./...

      - name: GO Vet
        run: go vet ./...

      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"

      - name: Install Golint
        run: go install golang.org/x/lint/golint@latest

      - name: Golint run
        run: golint ./...

      # - name: Run tests
      #   run: go test
