---
name: build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Go setup
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Go Verify
        run: go mod verify

      - name: Go Build
        run: go build -v ./...

      - name: Test
        run: go test -race ./...

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: go
          target-branch: ${{ github.ref_name }}
