---
name: App

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  app:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Go setup
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
          cache-dependency-path: |
            subdir/go.sum
            tools/go.sum`

      - name: Go Verify
        run: go mod verify

      - name: Go Build
        run: go build -v ./...

      - name: GO Vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      # - name: Run tests
      #   run: go test

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: go
          target-branch: ${{ github.ref_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: aimarjs/tyk-sre-assignment:${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}, aimarjs/tyk-sre-assignment:latest
